### ISSUE TITLE
Unable to use Refined Quartz

### ISSUE THREAD

**Issue by mysterious45** [Jamesdsj/TinkersCalibration#2]
Molten Refined Quartz is missing a texture, and is obtainable with alloying but not usable in casts, and there are no recipes for Refined Quartz toolparts.

**Comment by Jamesdsj** [comment]
You must be using the old-fashioned 1.0.1 version.
I no longer upload source code and releases to Github. Instead, the entire project is on mcmod.cn and the latest version is 1.1.0c for mc 1.19. Unfortunately, new features don't have English language files because I have little time.
If you want to have a try, go to mcmod.cn/class/10374.html. Good luck!
